import mongoose, { Document, Schema } from 'mongoose';

export interface IStaffTask extends Document {
  taskType: 'cleaning' | 'maintenance' | 'service' | 'banquet_setup' | 'restaurant_service';
  title: string;
  description: string;
  assignedTo: mongoose.Types.ObjectId;
  assignedBy?: mongoose.Types.ObjectId;
  room?: mongoose.Types.ObjectId;
  banquet?: mongoose.Types.ObjectId;
  area?: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: 'pending' | 'in_progress' | 'completed' | 'verified' | 'rejected';
  dueTime?: Date;
  startedAt?: Date;
  completedAt?: Date;
  verifiedAt?: Date;
  verifiedBy?: mongoose.Types.ObjectId;
  completionPhotos: string[];
  completionNotes?: string;
  rejectionReason?: string;
  relatedBooking?: mongoose.Types.ObjectId;
  isAutoGenerated: boolean;
  autoGeneratedReason?: string;
  estimatedDuration?: number;
  actualDuration?: number;
  createdAt: Date;
  updatedAt: Date;
}

const staffTaskSchema = new Schema<IStaffTask>({
  taskType: {
    type: String,
    enum: ['cleaning', 'maintenance', 'service', 'banquet_setup', 'restaurant_service'],
    required: true
  },
  title: { type: String, required: true },
  description: { type: String, required: true },
  assignedTo: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  assignedBy: { type: Schema.Types.ObjectId, ref: 'User' },
  room: { type: Schema.Types.ObjectId, ref: 'Room' },
  banquet: { type: Schema.Types.ObjectId, ref: 'Banquet' },
  area: { type: String },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high', 'urgent'],
    default: 'medium'
  },
  status: {
    type: String,
    enum: ['pending', 'in_progress', 'completed', 'verified', 'rejected'],
    default: 'pending'
  },
  dueTime: { type: Date },
  startedAt: { type: Date },
  completedAt: { type: Date },
  verifiedAt: { type: Date },
  verifiedBy: { type: Schema.Types.ObjectId, ref: 'User' },
  completionPhotos: [{ type: String }],
  completionNotes: { type: String },
  rejectionReason: { type: String },
  relatedBooking: { type: Schema.Types.ObjectId, ref: 'Booking' },
  isAutoGenerated: { type: Boolean, default: false },
  autoGeneratedReason: { type: String },
  estimatedDuration: { type: Number },
  actualDuration: { type: Number }
}, { timestamps: true });

staffTaskSchema.index({ assignedTo: 1, status: 1 });
staffTaskSchema.index({ room: 1 });
staffTaskSchema.index({ status: 1, priority: 1 });

export default mongoose.model<IStaffTask>('StaffTask', staffTaskSchema);
