import axios from '../config/axios';

export interface StaffTask {
  _id: string;
  taskType: 'cleaning' | 'maintenance' | 'service' | 'banquet_setup' | 'restaurant_service';
  room?: { _id: string; roomNumber: string };
  description: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: 'pending' | 'in_progress' | 'completed' | 'verified' | 'rejected';
  assignedTo: { _id: string; firstName: string; lastName: string };
  assignedBy?: { _id: string; firstName: string; lastName: string };
  deadline?: Date;
  startedAt?: Date;
  completedAt?: Date;
  photos?: string[];
  notes?: string;
  isAutoGenerated: boolean;
  verifiedBy?: { _id: string; firstName: string; lastName: string };
  verifiedAt?: Date;
  rejectionReason?: string;
  createdAt: Date;
}

export interface StaffProfile {
  _id: string;
  user: {
    _id: string;
    firstName: string;
    lastName: string;
    email: string;
    phoneNumber?: string;
  };
  staffId: string;
  department: string;
  staffType: 'housekeeping' | 'maintenance' | 'frontdesk' | 'restaurant' | 'banquet';
  address?: string;
  emergencyContact?: {
    name: string;
    relationship: string;
    phone: string;
  };
  performanceMetrics: {
    tasksCompleted: number;
    tasksRejected: number;
    averageCompletionTime: number;
    rating: number;
  };
  leaveBalance: {
    sick: number;
    casual: number;
    annual: number;
  };
  assignedManager?: { _id: string; firstName: string; lastName: string };
}

export interface StaffLeave {
  _id: string;
  staff: { _id: string; firstName: string; lastName: string };
  leaveType: 'sick' | 'casual' | 'annual' | 'unpaid';
  startDate: Date;
  endDate: Date;
  numberOfDays: number;
  reason: string;
  status: 'pending' | 'approved' | 'rejected';
  reviewedBy?: { _id: string; firstName: string; lastName: string };
  reviewedAt?: Date;
  reviewNotes?: string;
  appliedAt: Date;
}

export interface StaffNotification {
  _id: string;
  type: 'task_assigned' | 'task_approved' | 'task_rejected' | 'leave_approved' | 'leave_rejected' | 'urgent' | 'shift_update';
  title: string;
  message: string;
  relatedTask?: { _id: string; taskType: string };
  relatedLeave?: { _id: string; leaveType: string };
  isRead: boolean;
  priority: 'low' | 'medium' | 'high';
  createdAt: string;
}

// Tasks
export const getMyTasks = async (params?: { status?: string; priority?: string; taskType?: string }) => {
  const { data } = await axios.get('/staff/tasks', { params });
  return data;
};

export const getTaskById = async (taskId: string) => {
  const { data } = await axios.get(`/staff/tasks/${taskId}`);
  return data;
};

export const getMyTaskStats = async () => {
  const { data } = await axios.get('/staff/tasks/stats');
  return data;
};

export const startTask = async (taskId: string) => {
  const { data } = await axios.patch(`/staff/tasks/${taskId}/start`);
  return data;
};

export const completeTask = async (taskId: string, formData: FormData) => {
  const { data } = await axios.patch(`/staff/tasks/${taskId}/complete`, formData, {
    headers: { 'Content-Type': 'multipart/form-data' }
  });
  return data;
};

// Profile
export const getMyProfile = async () => {
  const { data } = await axios.get('/staff/profile');
  return data;
};

export const updateMyProfile = async (profileData: any) => {
  const { data } = await axios.patch('/staff/profile', profileData);
  return data;
};

export const getMyPerformanceMetrics = async () => {
  const { data } = await axios.get('/staff/profile/performance');
  return data;
};

export const getMyActivityLog = async () => {
  const { data } = await axios.get('/staff/profile/activity');
  return data;
};

// Leave
export const applyLeave = async (leaveData: any) => {
  const { data } = await axios.post('/staff/leaves', leaveData);
  return data;
};

export const getMyLeaves = async () => {
  const { data } = await axios.get('/staff/leaves');
  return data;
};

export const getLeaveBalance = async () => {
  const { data } = await axios.get('/staff/leaves/balance');
  return data;
};

export const cancelLeave = async (leaveId: string) => {
  const { data } = await axios.delete(`/staff/leaves/${leaveId}`);
  return data;
};

// Notifications
export const getMyNotifications = async () => {
  const { data } = await axios.get('/staff/notifications');
  return data;
};

export const markAsRead = async (notificationId: string) => {
  const { data } = await axios.patch(`/staff/notifications/${notificationId}/read`);
  return data;
};

export const markAllAsRead = async () => {
  const { data } = await axios.patch('/staff/notifications/read-all');
  return data;
};

export const getUnreadCount = async () => {
  const { data } = await axios.get('/staff/notifications/unread-count');
  return data;
};
