import { Request, Response } from 'express';
import StaffTask from '../models/StaffTask';
import StaffProfile from '../models/StaffProfile';
import StaffNotification from '../models/StaffNotification';
import Room from '../models/Room';
import Booking from '../models/Booking';
import User from '../models/User';
import path from 'path';
import fs from 'fs';

interface AuthRequest extends Request {
  user?: any;
}

// Auto-create cleaning task when guest checks out
export const createCheckoutCleaningTask = async (bookingId: string, roomId: string) => {
  try {
    console.log('🔍 Creating checkout cleaning task for room:', roomId);
    
    const housekeepingStaff = await StaffProfile.findOne({ 
      staffType: 'housekeeping',
      isActive: true 
    }).populate('user');

    if (!housekeepingStaff) {
      console.error('❌ No housekeeping staff available');
      return null;
    }

    console.log('✅ Found housekeeping staff:', housekeepingStaff.user);

    const room = await Room.findById(roomId);
    if (!room) {
      console.error('❌ Room not found');
      return null;
    }

    console.log('✅ Found room:', room.roomNumber);

    room.status = 'cleaning';
    await room.save();

    const task = new StaffTask({
      taskType: 'cleaning',
      title: `Clean Room ${room.roomNumber}`,
      description: `Complete cleaning of Room ${room.roomNumber} after guest checkout. Ensure all surfaces, bathroom, and amenities are thoroughly cleaned.`,
      assignedTo: housekeepingStaff.user._id,
      room: roomId,
      priority: 'high',
      status: 'pending',
      dueTime: new Date(Date.now() + 2 * 60 * 60 * 1000),
      relatedBooking: bookingId,
      isAutoGenerated: true,
      autoGeneratedReason: 'Guest checkout',
      estimatedDuration: 45
    });

    await task.save();
    console.log('✅ Task created:', task._id);

    await StaffNotification.create({
      recipient: housekeepingStaff.user._id.toString(),
      type: 'task_assigned',
      title: `New Cleaning Task - Room ${room.roomNumber}`,
      message: `You have been assigned to clean Room ${room.roomNumber} after guest checkout. Priority: High`,
      relatedTask: task._id,
      priority: 'high'
    });

    console.log(`✅ Auto-generated cleaning task for Room ${room.roomNumber} and notification sent`);
    return task;
  } catch (error) {
    console.error('❌ Error creating checkout cleaning task:', error);
    return null;
  }
};

// Auto-create maintenance task
export const createMaintenanceTask = async (
  roomId: string,
  issueDescription: string,
  reportedBy: string,
  priority: 'low' | 'medium' | 'high' | 'urgent' = 'medium'
) => {
  try {
    const maintenanceStaff = await StaffProfile.findOne({ 
      staffType: 'maintenance',
      isActive: true 
    }).populate('user');

    if (!maintenanceStaff) {
      console.error('No maintenance staff available');
      return null;
    }

    const room = await Room.findById(roomId);
    if (!room) return null;

    room.status = 'maintenance';
    await room.save();

    const task = new StaffTask({
      taskType: 'maintenance',
      title: `Maintenance Required - Room ${room.roomNumber}`,
      description: issueDescription,
      assignedTo: maintenanceStaff.user._id,
      room: roomId,
      priority: priority,
      status: 'pending',
      dueTime: priority === 'urgent' 
        ? new Date(Date.now() + 1 * 60 * 60 * 1000)
        : new Date(Date.now() + 4 * 60 * 60 * 1000),
      isAutoGenerated: true,
      autoGeneratedReason: 'Maintenance request',
      estimatedDuration: 60
    });

    await task.save();

    await StaffNotification.create({
      recipient: maintenanceStaff.user._id.toString(),
      type: 'task_assigned',
      title: `New Maintenance Task - Room ${room.roomNumber}`,
      message: `Maintenance required: ${issueDescription}. Priority: ${priority}`,
      relatedTask: task._id,
      priority: priority === 'urgent' ? 'high' : 'medium'
    });

    console.log(`✅ Auto-generated maintenance task for Room ${room.roomNumber}`);
    return task;
  } catch (error) {
    console.error('Error creating maintenance task:', error);
    return null;
  }
};

// Get my tasks
export const getMyTasks = async (req: AuthRequest, res: Response) => {
  try {
    const { status, priority, type } = req.query;
    
    const query: any = { assignedTo: req.user._id };
    
    if (status) query.status = status;
    if (priority) query.priority = priority;
    if (type) query.taskType = type;

    const tasks = await StaffTask.find(query)
      .populate('room', 'roomNumber')
      .populate('assignedBy', 'firstName lastName')
      .sort({ priority: -1, dueTime: 1 });

    res.json({ tasks });
  } catch (error) {
    console.error('Get my tasks error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// Get task by ID
export const getTaskById = async (req: AuthRequest, res: Response) => {
  try {
    const task = await StaffTask.findOne({
      _id: req.params.taskId,
      assignedTo: req.user._id
    })
      .populate('room', 'roomNumber type')
      .populate('assignedBy', 'firstName lastName')
      .populate('verifiedBy', 'firstName lastName');

    if (!task) {
      return res.status(404).json({ message: 'Task not found' });
    }

    res.json({ task });
  } catch (error) {
    console.error('Get task by ID error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// Start task
export const startTask = async (req: AuthRequest, res: Response) => {
  try {
    const task = await StaffTask.findOne({
      _id: req.params.taskId,
      assignedTo: req.user._id
    });

    if (!task) {
      return res.status(404).json({ message: 'Task not found' });
    }

    if (task.status !== 'pending') {
      return res.status(400).json({ message: 'Task already started or completed' });
    }

    task.status = 'in_progress';
    task.startedAt = new Date();
    await task.save();

    res.json({ message: 'Task started successfully', task });
  } catch (error) {
    console.error('Start task error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// Complete task with photo proof
export const completeTask = async (req: AuthRequest, res: Response) => {
  try {
    const { completionNotes } = req.body;
    const files = req.files as Express.Multer.File[];

    const task = await StaffTask.findOne({
      _id: req.params.taskId,
      assignedTo: req.user._id
    });

    if (!task) {
      return res.status(404).json({ message: 'Task not found' });
    }

    if (task.status !== 'in_progress' && task.status !== 'pending') {
      return res.status(400).json({ 
        message: `Cannot complete task with status: ${task.status}` 
      });
    }

    // Upload photos to local storage
    const photoUrls: string[] = [];
    if (files && files.length > 0) {
      // Files are already saved by multer with proper extensions
      for (const file of files) {
        // File path is relative to project root
        const relativePath = `/uploads/tasks/${file.filename}`;
        photoUrls.push(relativePath);
        console.log('Photo saved:', relativePath);
      }
    }

    const actualDuration = task.startedAt 
      ? Math.round((Date.now() - task.startedAt.getTime()) / 60000)
      : undefined;

    task.status = 'completed';
    task.completedAt = new Date();
    task.completionPhotos = photoUrls;
    task.completionNotes = completionNotes;
    task.actualDuration = actualDuration;
    await task.save();

    // Update staff profile statistics
    const staffProfile = await StaffProfile.findOne({ user: req.user._id });
    if (staffProfile) {
      staffProfile.performanceMetrics.tasksCompleted += 1;
      
      if (actualDuration) {
        const totalTasks = staffProfile.performanceMetrics.tasksCompleted;
        const currentAvg = staffProfile.performanceMetrics.averageCompletionTime;
        staffProfile.performanceMetrics.averageCompletionTime = 
          ((currentAvg * (totalTasks - 1)) + actualDuration) / totalTasks;
      }
      
      await staffProfile.save();
    }

    await StaffNotification.create({
      recipient: req.user._id,
      type: 'task_approved',
      title: 'Task Submitted for Verification',
      message: `Your task "${task.title}" has been submitted and is awaiting manager verification.`,
      relatedTask: task._id,
      priority: 'low'
    });

    res.json({ message: 'Task completed successfully', task });
  } catch (error) {
    console.error('Complete task error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// Get task statistics for dashboard
export const getMyTaskStats = async (req: AuthRequest, res: Response) => {
  try {
    const [pending, inProgress, completed, rejected] = await Promise.all([
      StaffTask.countDocuments({ assignedTo: req.user._id, status: 'pending' }),
      StaffTask.countDocuments({ assignedTo: req.user._id, status: 'in_progress' }),
      StaffTask.countDocuments({ assignedTo: req.user._id, status: 'verified' }),
      StaffTask.countDocuments({ assignedTo: req.user._id, status: 'rejected' })
    ]);

    const todayStart = new Date();
    todayStart.setHours(0, 0, 0, 0);

    const completedToday = await StaffTask.countDocuments({
      assignedTo: req.user._id,
      status: { $in: ['completed', 'verified'] },
      completedAt: { $gte: todayStart }
    });

    const urgentTasks = await StaffTask.countDocuments({
      assignedTo: req.user._id,
      priority: 'urgent',
      status: { $in: ['pending', 'in_progress'] }
    });

    res.json({
      stats: {
        pending,
        inProgress,
        completed,
        rejected,
        completedToday,
        urgentTasks
      }
    });
  } catch (error) {
    console.error('Get task stats error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};
